# Generated by Django 4.2.4 on 2023-09-10 23:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('overviewsite', '0003_alter_agritectusers_allocated_space'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drives',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('drive_name', models.CharField(max_length=25)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('drive_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overviewsite.agritectusers')),
            ],
        ),
        migrations.CreateModel(
            name='PlantDatabase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlantsAnalyzed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('plant_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Healthy', 'Healthy'), ('Sick', 'Sick')], max_length=10)),
                ('disease_name', models.CharField(max_length=255)),
                ('image_path', models.ImageField(upload_to='analyzed_images/')),
                ('date_detected', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='overviewsite.agritectusers')),
            ],
        ),
        migrations.CreateModel(
            name='PlantDiseases',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('disease_name', models.CharField(max_length=255)),
                ('causes', models.TextField()),
                ('prevention_measures', models.TextField()),
                ('cures', models.TextField()),
                ('plantid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersite.plantdatabase')),
            ],
        ),
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator(message='Path must start with a slash, and can contain letters, digits,hyphens, underscores, dots, at signs, plus signs, and slashes.', regex='^[/\\w.@+-]*(?:[/\\w@+-]+)*$')])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('drive_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersite.drives')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=1000, validators=[django.core.validators.RegexValidator(message='Path must start with a slash, and can contain letters, digits,hyphens, underscores, dots, at signs, plus signs, and slashes.', regex='^[/\\w.@+-]*(?:[/\\w@+-]+)*$')])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('file_ext', models.CharField(blank=True, max_length=100)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('drive_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usersite.drives')),
                ('folder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersite.folders')),
            ],
        ),
    ]
