# Generated by Django 4.2.4 on 2023-09-11 21:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('overviewsite', '0003_alter_agritectusers_allocated_space'),
        ('usersite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deficiency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nutrient_name', models.CharField(help_text='Name of the nutrient causing deficiency', max_length=255)),
                ('symptoms', models.TextField(help_text='Symptoms of the deficiency')),
                ('recommended_actions', models.TextField(help_text='Recommended actions to address the deficiency')),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='deficiency_images/')),
            ],
        ),
        migrations.AddField(
            model_name='plantdiseases',
            name='description',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantsanalyzed',
            name='disease_type',
            field=models.CharField(choices=[('None', 'None'), ('Deficiency', 'Deficiency'), ('Illness/Infection', 'Illness/Infection')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plantsanalyzed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overviewsite.agritectusers'),
        ),
    ]
