# Generated by Django 4.2.4 on 2023-09-11 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersite', '0003_alter_plantdiseases_causes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdiseases',
            name='causes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plantdiseases',
            name='plantid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersite.plantdatabase'),
        ),
    ]
